package br.gov.serpro.infoconv.ws.cnpj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Apr 05 10:33:24 BRT 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", name = "ConsultarCNPJSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultarCNPJSoap {

    @WebResult(name = "ConsultarCNPJP3Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    @RequestWrapper(localName = "ConsultarCNPJP3", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP3")
    @WebMethod(operationName = "ConsultarCNPJP3", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP3")
    @ResponseWrapper(localName = "ConsultarCNPJP3Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP3Response")
    public br.gov.serpro.infoconv.ws.cnpj.ArrayOfCNPJPerfil3 consultarCNPJP3(
        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    @WebResult(name = "ConsultarCNPJP3TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    @RequestWrapper(localName = "ConsultarCNPJP3T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP3T")
    @WebMethod(operationName = "ConsultarCNPJP3T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP3T")
    @ResponseWrapper(localName = "ConsultarCNPJP3TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP3TResponse")
    public br.gov.serpro.infoconv.ws.cnpj.ArrayOfCNPJPerfil3 consultarCNPJP3T(
        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    @WebResult(name = "ConsultarCNPJP2Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    @RequestWrapper(localName = "ConsultarCNPJP2", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP2")
    @WebMethod(operationName = "ConsultarCNPJP2", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP2")
    @ResponseWrapper(localName = "ConsultarCNPJP2Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP2Response")
    public br.gov.serpro.infoconv.ws.cnpj.ArrayOfCNPJPerfil2 consultarCNPJP2(
        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    @WebResult(name = "ConsultarCNPJP2TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    @RequestWrapper(localName = "ConsultarCNPJP2T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP2T")
    @WebMethod(operationName = "ConsultarCNPJP2T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP2T")
    @ResponseWrapper(localName = "ConsultarCNPJP2TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP2TResponse")
    public br.gov.serpro.infoconv.ws.cnpj.ArrayOfCNPJPerfil2 consultarCNPJP2T(
        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    @WebResult(name = "ConsultarCNPJP1TResult", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    @RequestWrapper(localName = "ConsultarCNPJP1T", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP1T")
    @WebMethod(operationName = "ConsultarCNPJP1T", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP1T")
    @ResponseWrapper(localName = "ConsultarCNPJP1TResponse", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP1TResponse")
    public br.gov.serpro.infoconv.ws.cnpj.ArrayOfCNPJPerfil1 consultarCNPJP1T(
        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );

    @WebResult(name = "ConsultarCNPJP1Result", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
    @RequestWrapper(localName = "ConsultarCNPJP1", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP1")
    @WebMethod(operationName = "ConsultarCNPJP1", action = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJP1")
    @ResponseWrapper(localName = "ConsultarCNPJP1Response", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.serpro.infoconv.ws.cnpj.ConsultarCNPJP1Response")
    public br.gov.serpro.infoconv.ws.cnpj.ArrayOfCNPJPerfil1 consultarCNPJP1(
        @WebParam(name = "CNPJ", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://hom-infoconv.receita.fazenda.gov.br/ws/cnpj/")
        java.lang.String cpfUsuario
    );
}
