
/*
 * 
 */

package br.gov.serpro.infoconv.ws.cpf;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Apr 05 10:30:43 BRT 2016
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "ConsultarCPF", 
                  wsdlLocation = "https://infoconv.receita.fazenda.gov.br/ws/cpf/consultarcpf.asmx?wsdl",
                  targetNamespace = "https://infoconv.receita.fazenda.gov.br/ws/cpf/") 
public class ConsultarCPF extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("https://infoconv.receita.fazenda.gov.br/ws/cpf/", "ConsultarCPF");
    public final static QName ConsultarCPFSoap12 = new QName("https://infoconv.receita.fazenda.gov.br/ws/cpf/", "ConsultarCPFSoap12");
    public final static QName ConsultarCPFSoap = new QName("https://infoconv.receita.fazenda.gov.br/ws/cpf/", "ConsultarCPFSoap");
    static {
        URL url = null;
        url =  ConsultarCPF.class.getResource("/META-INF/wsdl/consultarcpf.wsdl");
        WSDL_LOCATION = url;
    }

    public ConsultarCPF(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultarCPF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarCPF() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns ConsultarCPFSoap
     */
    @WebEndpoint(name = "ConsultarCPFSoap12")
    public ConsultarCPFSoap getConsultarCPFSoap12() {
        return super.getPort(ConsultarCPFSoap12, ConsultarCPFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarCPFSoap
     */
    @WebEndpoint(name = "ConsultarCPFSoap12")
    public ConsultarCPFSoap getConsultarCPFSoap12(WebServiceFeature... features) {
        return super.getPort(ConsultarCPFSoap12, ConsultarCPFSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns ConsultarCPFSoap
     */
    @WebEndpoint(name = "ConsultarCPFSoap")
    public ConsultarCPFSoap getConsultarCPFSoap() {
        return super.getPort(ConsultarCPFSoap, ConsultarCPFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarCPFSoap
     */
    @WebEndpoint(name = "ConsultarCPFSoap")
    public ConsultarCPFSoap getConsultarCPFSoap(WebServiceFeature... features) {
        return super.getPort(ConsultarCPFSoap, ConsultarCPFSoap.class, features);
    }

}
